name: 'Deploy Simple Container Client Stack (Self-Contained)'
description: 'Complete deployment solution - embeds ALL workflow functionality, no additional actions required'
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  # Required inputs
  stack-name:
    description: 'Name of the stack to deploy'
    required: true
  environment:
    description: 'Target environment (staging, prod, etc.)'
    required: true
    default: 'staging'
  sc-config:
    description: 'Simple Container configuration (SC_CONFIG secret content)'
    required: true

  # Simple Container options (pre-built in action image)
  sc-deploy-flags:
    description: 'Additional flags for sc deploy command'
    required: false
    default: ''

  # Version management
  version-suffix:
    description: 'Suffix for generated version (e.g., -beta, -rc1)'
    required: false
    default: ''
  app-image-version:
    description: 'Override version with specific image version'
    required: false

  # PR preview options
  pr-preview:
    description: 'Enable PR preview mode'
    required: false
    default: 'false'
  preview-domain-base:
    description: 'Base domain for PR preview subdomains'
    required: false
    default: 'preview.mycompany.com'

  # Configuration options
  stack-yaml-config:
    description: 'Additional YAML config to append (base64 encoded)'
    required: false
  stack-yaml-config-encrypted:
    description: 'Whether stack-yaml-config is encrypted'
    required: false
    default: 'false'

  # Validation
  validation-command:
    description: 'Optional command to run after deployment'
    required: false

  # Notification options
  cc-on-start:
    description: 'Tag deployment watchers on start'
    required: false
    default: 'true'
  slack-webhook-url:
    description: 'Custom Slack webhook URL (optional)'
    required: false
  discord-webhook-url:
    description: 'Custom Discord webhook URL (optional)'
    required: false

  # Runner options
  runner:
    description: 'GitHub Actions runner type being used'
    required: false
    default: 'ubuntu-latest'

outputs:
  version:
    description: 'Generated or provided version for the deployment'
  environment:
    description: 'Environment that was deployed to'
  stack-name:
    description: 'Stack name that was deployed'
  duration:
    description: 'Deployment duration (e.g., 5m23s)'
  status:
    description: 'Deployment status (success/failure/cancelled)'
  build-url:
    description: 'URL to the GitHub Actions build'
  commit-sha:
    description: 'Git commit SHA that was deployed'
  branch:
    description: 'Git branch that was deployed'
  preview-url:
    description: 'Preview URL (if PR preview enabled)'

runs:
  using: 'docker'
  image: 'docker://simplecontainer/github-action-deploy-client-stack:latest'
  env:
    # Core deployment inputs
    STACK_NAME: ${{ inputs.stack-name }}
    ENVIRONMENT: ${{ inputs.environment }}
    SC_CONFIG: ${{ inputs.sc-config }}
    
    # Simple Container configuration (binary pre-built in image)
    SC_DEPLOY_FLAGS: ${{ inputs.sc-deploy-flags }}
    
    # Version management
    VERSION_SUFFIX: ${{ inputs.version-suffix }}
    APP_IMAGE_VERSION: ${{ inputs.app-image-version }}
    
    # PR preview configuration
    PR_PREVIEW: ${{ inputs.pr-preview }}
    PREVIEW_DOMAIN_BASE: ${{ inputs.preview-domain-base }}
    
    # Stack configuration
    STACK_YAML_CONFIG: ${{ inputs.stack-yaml-config }}
    STACK_YAML_CONFIG_ENCRYPTED: ${{ inputs.stack-yaml-config-encrypted }}
    
    # Validation
    VALIDATION_COMMAND: ${{ inputs.validation-command }}
    
    # Notification configuration
    CC_ON_START: ${{ inputs.cc-on-start }}
    SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }}
    DISCORD_WEBHOOK_URL: ${{ inputs.discord-webhook-url }}
    
    # Runner configuration
    RUNNER: ${{ inputs.runner }}
    
    # GitHub context (automatically available in actions)
    GITHUB_TOKEN: ${{ github.token }}
    GITHUB_REPOSITORY: ${{ github.repository }}
    GITHUB_SHA: ${{ github.sha }}
    GITHUB_REF_NAME: ${{ github.ref_name }}
    GITHUB_ACTOR: ${{ github.actor }}
    GITHUB_RUN_ID: ${{ github.run_id }}
    GITHUB_RUN_NUMBER: ${{ github.run_number }}
    GITHUB_SERVER_URL: ${{ github.server_url }}
    GITHUB_WORKSPACE: ${{ github.workspace }}
    GITHUB_OUTPUT: ${{ github.output }}
    GITHUB_STEP_SUMMARY: ${{ github.step_summary }}
    
    # PR context for previews
    PR_NUMBER: ${{ github.event.pull_request.number }}
    PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
    PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
    PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
    
    # Commit context
    COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
