name: 'Provision Simple Container Parent Stack'
description: 'Provision a Simple Container parent stack using internal SC APIs'
branding:
  icon: 'layers'
  color: 'blue'

inputs:
  stack-name:
    description: 'Name of the parent stack to provision'
    required: true
  sc-config:
    description: 'Simple Container configuration (SC_CONFIG secret content)'
    required: true
  environment:
    description: 'Target environment profile'
    required: false
    default: 'default'
  slack-webhook-url:
    description: 'Slack webhook URL for notifications (optional)'
    required: false
  discord-webhook-url:
    description: 'Discord webhook URL for notifications (optional)'
    required: false

outputs:
  stack-name:
    description: 'Parent stack name that was provisioned'
  duration:
    description: 'Provisioning duration'
  status:
    description: 'Provisioning status (success/failure)'

runs:
  using: 'docker'
  image: 'docker://simplecontainer/github-actions:latest'
  env:
    GITHUB_ACTION_TYPE: 'provision-parent-stack'
    STACK_NAME: ${{ inputs.stack-name }}
    ENVIRONMENT: ${{ inputs.environment }}
    SC_CONFIG: ${{ inputs.sc-config }}
    SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }}
    DISCORD_WEBHOOK_URL: ${{ inputs.discord-webhook-url }}
