name: 'Destroy Simple Container Client Stack'
description: 'Destroy a Simple Container client stack using internal SC APIs'
branding:
  icon: 'trash-2'
  color: 'red'

inputs:
  stack-name:
    description: 'Name of the stack to destroy'
    required: true
  environment:
    description: 'Target environment (staging, prod, etc.)'
    required: true
  sc-config:
    description: 'Simple Container configuration (SC_CONFIG secret content)'
    required: true
  auto-confirm:
    description: 'Automatically confirm destruction without prompts'
    required: false
    default: 'false'
  skip-backup:
    description: 'Skip creating backups before destruction'
    required: false
    default: 'false'
  pr-preview:
    description: 'Destroy PR preview environment'
    required: false
    default: 'false'
  pr-number:
    description: 'Pull request number for preview environments'
    required: false
  token:
    description: 'GitHub token for repository access'
    required: false
    default: ${{ github.token }}
  repository:
    description: 'Repository name with owner (e.g., actions/checkout)'
    required: false
    default: ${{ github.repository }}
  ref:
    description: 'The branch, tag or SHA to checkout'
    required: false
    default: ${{ github.sha }}

outputs:
  environment:
    description: 'Environment that was destroyed'
  stack-name:
    description: 'Stack name that was destroyed'
  duration:
    description: 'Destruction duration'
  status:
    description: 'Destruction status (success/failure)'

runs:
  using: 'docker'
  image: 'docker://simplecontainer/github-actions:staging'
  env:
    GITHUB_ACTION_TYPE: 'destroy-client-stack'
    STACK_NAME: ${{ inputs.stack-name }}
    ENVIRONMENT: ${{ inputs.environment }}
    SC_CONFIG: ${{ inputs.sc-config }}
    AUTO_CONFIRM: ${{ inputs.auto-confirm }}
    SKIP_BACKUP: ${{ inputs.skip-backup }}
    PR_PREVIEW: ${{ inputs.pr-preview }}
    PR_NUMBER: ${{ inputs.pr-number }}
    GITHUB_TOKEN: ${{ inputs.token }}
    GITHUB_REPOSITORY: ${{ inputs.repository }}
    GITHUB_SHA: ${{ inputs.ref }}
    GITHUB_REF: ${{ inputs.ref }}
