name: 'Destroy Simple Container Client Stack'
description: 'Destroy a Simple Container client stack using internal SC APIs'
branding:
  icon: 'trash-2'
  color: 'red'

inputs:
  stack-name:
    description: 'Name of the stack to destroy'
    required: true
  environment:
    description: 'Target environment (staging, prod, etc.)'
    required: true
  sc-config:
    description: 'Simple Container configuration (SC_CONFIG secret content)'
    required: true

outputs:
  environment:
    description: 'Environment that was destroyed'
  stack-name:
    description: 'Stack name that was destroyed'
  duration:
    description: 'Destruction duration'
  status:
    description: 'Destruction status (success/failure)'

runs:
  using: 'docker'
  image: 'docker://simplecontainer/github-actions:latest'
  env:
    GITHUB_ACTION_TYPE: 'destroy-client-stack'
    STACK_NAME: ${{ inputs.stack-name }}
    ENVIRONMENT: ${{ inputs.environment }}
    SC_CONFIG: ${{ inputs.sc-config }}
