name: 'Destroy Simple Container Parent Stack'
description: 'Destroy a Simple Container parent stack using internal SC APIs'
branding:
  icon: 'x-circle'
  color: 'red'

inputs:
  stack-name:
    description: 'Name of the parent stack to destroy'
    required: true
  sc-config:
    description: 'Simple Container configuration (SC_CONFIG secret content)'
    required: true

outputs:
  stack-name:
    description: 'Parent stack name that was destroyed'
  duration:
    description: 'Destruction duration'
  status:
    description: 'Destruction status (success/failure)'

runs:
  using: 'docker'
  image: 'docker://simplecontainer/github-actions:latest'
  env:
    GITHUB_ACTION_TYPE: 'destroy-parent-stack'
    STACK_NAME: ${{ inputs.stack-name }}
    SC_CONFIG: ${{ inputs.sc-config }}
