name: 'Destroy Simple Container Parent Stack'
description: 'Destroy a Simple Container parent stack using internal SC APIs'
branding:
  icon: 'x-circle'
  color: 'red'

inputs:
  stack-name:
    description: 'Name of the parent stack to destroy'
    required: true
  sc-config:
    description: 'Simple Container configuration (SC_CONFIG secret content)'
    required: true
  auto-confirm:
    description: 'Automatically confirm destruction without prompts'
    required: false
    default: 'false'
  skip-backup:
    description: 'Skip creating backups before destruction'
    required: false
    default: 'false'
  notify-on-completion:
    description: 'Send notifications when destruction completes'
    required: false
    default: 'true'
  token:
    description: 'GitHub token for repository access'
    required: false
    default: ${{ github.token }}
  repository:
    description: 'Repository name with owner (e.g., actions/checkout)'
    required: false
    default: ${{ github.repository }}
  ref:
    description: 'The branch, tag or SHA to checkout'
    required: false
    default: ${{ github.sha }}

outputs:
  stack-name:
    description: 'Parent stack name that was destroyed'
  duration:
    description: 'Destruction duration'
  status:
    description: 'Destruction status (success/failure)'

runs:
  using: 'docker'
  image: 'docker://simplecontainer/github-actions:staging'
  env:
    GITHUB_ACTION_TYPE: 'destroy-parent-stack'
    STACK_NAME: ${{ inputs.stack-name }}
    SC_CONFIG: ${{ inputs.sc-config }}
    AUTO_CONFIRM: ${{ inputs.auto-confirm }}
    SKIP_BACKUP: ${{ inputs.skip-backup }}
    NOTIFY_ON_COMPLETION: ${{ inputs.notify-on-completion }}
    GITHUB_TOKEN: ${{ inputs.token }}
    GITHUB_REPOSITORY: ${{ inputs.repository }}
    GITHUB_SHA: ${{ inputs.ref }}
    GITHUB_REF: ${{ inputs.ref }}
