# VPA Infrastructure - Secrets Configuration
# File: .sc/stacks/infrastructure/secrets.yaml

schemaVersion: 1.0

# Authentication providers
auth:
  gcloud:
    type: gcp-service-account
    projectId: "my-gcp-project-12345"
    keyLocation: global
    credentials: |
      {
        "type": "service_account",
        "project_id": "my-gcp-project-12345",
        "private_key_id": "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0",
        "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC8Q7HgL...\n-----END PRIVATE KEY-----\n",
        "client_email": "vpa-demo-service@my-gcp-project-12345.iam.gserviceaccount.com",
        "client_id": "123456789012345678901",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/vpa-demo-service%40my-gcp-project-12345.iam.gserviceaccount.com"
      }

# Secret values - These are concrete values, not placeholders
values:
  # MongoDB Atlas credentials
  mongodb-atlas-project-id: "507f1f77bcf86cd799439011"
  mongodb-atlas-public-key: "abcdefgh"
  mongodb-atlas-private-key: "12345678-1234-1234-1234-123456789012"
  
  # Application secrets for VPA demo
  app-jwt-secret: "jwt-secret-key-a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"
  app-encryption-key: "32-char-encryption-key-123456789012"

# Note: In production, these values should be:
# 1. Generated securely with proper entropy
# 2. Rotated regularly (quarterly recommended)
# 3. Stored in a secure key management system
# 4. Never committed to version control in plain text
# This example shows the structure with dummy values for demonstration
