// Code generated by mockery v2.42.2. DO NOT EDIT.

package pulumi_mocks

import (
	context "context"

	api "github.com/simple-container-com/api/pkg/api"

	mock "github.com/stretchr/testify/mock"
)

// PulumiMock is an autogenerated mock type for the Pulumi type
type PulumiMock struct {
	mock.Mock
}

// CancelStack provides a mock function with given fields: ctx, cfg, parentStack, params
func (_m *PulumiMock) CancelStack(ctx context.Context, cfg *api.ConfigFile, parentStack api.Stack, params api.DeployParams) error {
	ret := _m.Called(ctx, cfg, parentStack, params)

	if len(ret) == 0 {
		panic("no return value specified for CancelStack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.ConfigFile, api.Stack, api.DeployParams) error); ok {
		r0 = rf(ctx, cfg, parentStack, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeployStack provides a mock function with given fields: ctx, cfg, stack, params
func (_m *PulumiMock) DeployStack(ctx context.Context, cfg *api.ConfigFile, stack api.Stack, params api.DeployParams) error {
	ret := _m.Called(ctx, cfg, stack, params)

	if len(ret) == 0 {
		panic("no return value specified for DeployStack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.ConfigFile, api.Stack, api.DeployParams) error); ok {
		r0 = rf(ctx, cfg, stack, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DestroyChildStack provides a mock function with given fields: ctx, cfg, stack, params
func (_m *PulumiMock) DestroyChildStack(ctx context.Context, cfg *api.ConfigFile, stack api.Stack, params api.DestroyParams) error {
	ret := _m.Called(ctx, cfg, stack, params)

	if len(ret) == 0 {
		panic("no return value specified for DestroyChildStack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.ConfigFile, api.Stack, api.DestroyParams) error); ok {
		r0 = rf(ctx, cfg, stack, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DestroyParentStack provides a mock function with given fields: ctx, cfg, parentStack
func (_m *PulumiMock) DestroyParentStack(ctx context.Context, cfg *api.ConfigFile, parentStack api.Stack) error {
	ret := _m.Called(ctx, cfg, parentStack)

	if len(ret) == 0 {
		panic("no return value specified for DestroyParentStack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.ConfigFile, api.Stack) error); ok {
		r0 = rf(ctx, cfg, parentStack)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PreviewStack provides a mock function with given fields: ctx, cfg, parentStack, params
func (_m *PulumiMock) PreviewStack(ctx context.Context, cfg *api.ConfigFile, parentStack api.Stack, params api.DeployParams) (*api.PreviewResult, error) {
	ret := _m.Called(ctx, cfg, parentStack, params)

	if len(ret) == 0 {
		panic("no return value specified for PreviewStack")
	}

	var r0 *api.PreviewResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.ConfigFile, api.Stack, api.DeployParams) (*api.PreviewResult, error)); ok {
		return rf(ctx, cfg, parentStack, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *api.ConfigFile, api.Stack, api.DeployParams) *api.PreviewResult); ok {
		r0 = rf(ctx, cfg, parentStack, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.PreviewResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *api.ConfigFile, api.Stack, api.DeployParams) error); ok {
		r1 = rf(ctx, cfg, parentStack, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProvisionStack provides a mock function with given fields: ctx, cfg, stack
func (_m *PulumiMock) ProvisionStack(ctx context.Context, cfg *api.ConfigFile, stack api.Stack) error {
	ret := _m.Called(ctx, cfg, stack)

	if len(ret) == 0 {
		panic("no return value specified for ProvisionStack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.ConfigFile, api.Stack) error); ok {
		r0 = rf(ctx, cfg, stack)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetConfigReader provides a mock function with given fields: _a0
func (_m *PulumiMock) SetConfigReader(_a0 api.ProvisionerFieldConfigReaderFunc) {
	_m.Called(_a0)
}

// SetPublicKey provides a mock function with given fields: pubKey
func (_m *PulumiMock) SetPublicKey(pubKey string) {
	_m.Called(pubKey)
}

// NewPulumiMock creates a new instance of PulumiMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPulumiMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PulumiMock {
	mock := &PulumiMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
